'use strict';
module.exports = {
  search(lg) {
    return this.data[lg];
  },
  data: {
    'command_ping_description': 'Displays bot pings',
    'command_ban_description': 'Ban a member from the server',
    'command_ban_invalidPosition':
      'You are not in the ban position of this user',
    'command_ban_MeInvalidePosition': 'I am not able to ban this user',
    'command_ban_success': 'User has been banned',
    'command_ban_error': 'I couldn\'t ban this user',
    'command_kick_description': 'Kick a member from the server',
    'command_kick_invalidPosition':
      'You are not in the Kick position of this user',
    'value_not_found': '',
    'command_kick_MeInvalidePosition': 'I am not able to Kick this user',
    'command_kick_success': 'User has been Kicked',
    'command_kick_error': 'I couldn\'t Kick this user',
    'command_help_description': 'Show all bot commands',
    'command_help_title': 'Here is my list of all my orders',
    'command_help_command': 'Here is the order information',
    'command_music_userNoJoin': 'You are not connected to a voice channel',
    'command_music_occured': 'I\'m already in a voice channel',
    'command_music_finish': 'The playlist is finished',
    'command_music_listMusic': 'List of music',
    'command_music_choiceFooter': 'Send `cancel` for cancel :p',
    'command_music_choiceInvalid': 'This choice is not valid',
    'command_music_choiceNotFound': 'This choice is not part of the selection',
    'command_music_addPlaylist': 'music added to the playlist',
    'command_music_choiceStop': 'You canceled the selection',
    'command_music_timeout': 'You have not selected music in time',
    'commande_music_played': 'I played now',
    'commande_music_not_played': 'I not played now',
    'command_music_matchChannel': 'I\'m already in your voice room',
    'command_music_noPermissions': 'You cannot add the bot by voice',
    'command_nsfw_not_authorized':
      'You must be in an nsfw salon to execute this command',
    'command_dm_not_authorized':
      'You must be in a guild to execute this command',
    'command_disable': 'This command is disabled',
    'command_broadcast_jpop_description':
      'Connects to a Jpop radio',
    'command_broadcast_kpop_description':
      'Connects to a Kpop radio',
    'command_broadcast_actualPlaying':
      'Current music is {{title}}',
    'command_purge_description': 'Delete x number of messages',
    'command_purge_error': 'An error occured',
    'command_purge_success': 'I deleted {{size}} messages',
    'command_lmgtfy_description': 'Research lmgtfy',
    'command_animal_description': 'Send an animal picture',
    'command_car_description': 'Send an car picture',
    'command_beautiful_description': 'Send a beautiful image',
    'command_black&white_description':
      'Puts your profile picture in black & white',
    'command_blur_description': 'Blur your profile picture',
    'command_cat_description': 'Send a picture of a cat',
    'command_comics_description': 'Send a picture of a comic book',
    'command_contrast_description': 'Highlights your profile photo',
    'command_convolute_description': 'Put your profile photo in convolute',
    'command_cosplay_description': 'Send a picture of a cosplay',
    'command_dog_description': 'Send a picture of a dog',
    'command_dragonball_description': 'Send a dragonball image',
    'command_emma_description': 'Send an image of an Emma',
    'command_espace_description': 'Send a picture of space',
    'command_facepalm_description': 'Send a facepalm image',
    'command_food_description': 'Send a food image',
    'command_gay_description': 'Turn your profile picture to gay',
    'command_girl_description': 'Send a picture of a girl',
    'command_invert_description': 'Invert your profile photo',
    'command_karaba_description': 'Send a picture of karaba',
    'command_m&ms_description': 'Sends an image of a m&ms',
    'command_mange_description': 'Send a manga image',
    'command_missing_description': 'Send a missing image',
    'command_nature_description': 'Send a picture of nature',
    'command_pixel_description': 'Puts your profile picture in pixels',
    'command_prison_description': 'Send a prison picture',
    'command_sepia_description': 'Set your profile photo to sepia',
    'command_tatoo_description': 'Send a tatoo image',
    'command_thomas_description': 'Send an image of Thomas',
    'command_triggered_description': 'Sends a triggered image',
    'command_urban_description': 'Send a picture of the city',
    'command_vangogh_description': 'Send a picture of Vangogh',
    'command_wallpaper_description': 'Send a wallpaper',
    'command_wanted_description': 'Send a wanted image',
    'command_leave_description': 'Disconnect the bot from the voice room',
    'command_smug_description': 'Send an image of smug',
    'command_baka_description': 'Send an image of baka',
    'command_tickle_description': 'Send an image of tickle',
    'command_slap_description': 'Send an image of slap',
    'command_poke_description': 'Send an image of poke',
    'command_pat_description': 'Send an image of pat',
    'command_neko_description': 'Send an image of neko',
    'command_nekogif_description': 'Send an image of nekogif',
    'command_moew_description': 'Send an image of moew',
    'command_lizard_description': 'Send an image of lizard',
    'command_kiss_description': 'Send an image of kiss',
    'command_hug_description': 'Send an image of hug',
    'command_foxgirl_description': 'Send an image of foxgirl',
    'command_feed_description': 'Send an image of feed',
    'command_cuddle_description': 'Send an image of cuddle',
    'command_kemonomimi_description': 'Send an image of kemonomimi',
    'command_holo_description': 'Send an image of holo',
    'command_goose_description': 'Send an image of goose',
    'command_gecg_description': 'Send an image of gecg',
    'command_avatar_description': 'Send an image of avatar',
    'command_why_description': 'Send a question (english only)',
    'command_cattext_description': 'Envoie un cat text',
    'command_8ball_description': 'Answer your questions',
    'command_owoified_description': 'OwOify your text',
    'command_pause_description': 'pause your music',
    'command_music_isPause': 'Music is already paused',
    'command_resume_description': 'Resume music',
    'command_music_isResume': 'Music is not paused',
    'command_queue_description': 'Display playlist',
    'command_music_notQueue': 'The playlist is empty',
    'command_music_queue': 'Here is your playlist',
    'command_volume_defined': 'The volume is set to {{volume}}%',
    'command_img_notShow': 'The image is not displayed? click here.',
    'member_missing_permission': 'You do not have the necessary permissions',
    'member_not_found': 'I cannot find the member in the server',
    'client_missing_permissions':
      // eslint-disable-next-line max-len
      'I don\'t have the necessary permissions.\nList of required permissions -> {{map}}',
    'command_queue_select': '{{emote}} Please select \`clear\` for arguments',
    'command_queue_choose':
      '{{emote}} Please choose between \`all\` or a \`number\`',
    'command_destroy_noInit': 'No music initiated',
    'command_destroy_noPlaying': 'I not played now',
    'command_destroy_noPerm': 'You do not have permission',
    'command_favorite_saving': 'Saving {{emote}}',
    'command_favorite_noPlaylist': 'This playlist is empty',
    'command_favorite_enterName':
      'Please enter name, example: \`{{prefix}}favorite save myPlaylist\`',
    'command_favorite_save_embed_title': 'your favorite list',
    'command_favorite_successful': 'successful {{emote}}',
    'command_favorite_failed': 'failed {{emote}}',
    'command_favorite_nameUsed': 'The name is already in use',
    'command_favorite_selectNumber': 'Please select a number',
    'command_favorite_selectValidNumber': 'Please select a valid number',
    'command_favorite_delete_embed_title': 'your favorite list',
    'command_favorite_noFavorite': 'no favorites',
    'command_favorite_default_embed_title': 'your favorite list',
    'command_kpop_requireJoin': 'You must join the lounge before',
    'command_kpop_missingPermission':
      'You cannot add the bot by voice',
    'command_jpop_requireJoin': 'You must join the lounge before',
    'command_jpop_missingPermission':
      'You cannot add the bot by voice',
    'command_leave_noPerm': 'You do not have permission',
    'command_loop_repeat_radio': 'You cannot repeat a radio',
    'command_loop_noPlaying': 'I don\'t play music',
    'command_pause_noPermission': 'You do not have permission',
    'command_pause_noCutMusic': 'You can\'t cut the music',
    'command_skip_noPermission': 'You do not have permission',
    'command_skipto_noPermission': 'You do not have permission',
    'value_is_not_a_number': 'value is not a number',
    'command_volume_noPermission': 'You do not have permission',
    'command_volume_useboost':
      'Please use boost argument: \`{{prefix}}volume {{query}} boost\`',
  },
};
